export const data =
  [{
    "id": 1,
    "image": "http://dummyimage.com/167x100.png/cc0000/ffffff",
    "intern_name": "Payment Adjustment Coordinator",
    "mode": "Online",
    "location": "Poland",
    "posted": "9 days ago",
    "company": "Bluejam",
    "stipend": "10000",
    "openings": 24,
    "link1": "nhs.uk",
    "link2": "businessweek.com"
  }, {
    "id": 2,
    "image": "http://dummyimage.com/206x100.png/dddddd/000000",
    "intern_name": "Payment Adjustment Coordinator",
    "mode": "hybrid",
    "location": "China",
    "posted": "9 days ago",
    "company": "Topdrive",
    "stipend": "$6.30",
    "openings": 8,
    "link1": "hao123.com",
    "link2": "statcounter.com"
  }, {
    "id": 3,
    "image": "http://dummyimage.com/141x100.png/dddddd/000000",
    "intern_name": "Senior Quality Engineer",
    "mode": "In-Office",
    "location": "Philippines",
    "posted": "9 days ago",
    "company": "Voonder",
    "stipend": "$3.74",
    "openings": 34,
    "link1": "skype.com",
    "link2": "nyu.edu"
  }, {
    "id": 4,
    "image": "http://dummyimage.com/145x100.png/ff4444/ffffff",
    "intern_name": "Librarian",
    "mode": "In-Office",
    "location": "Sweden",
    "posted": "5 days ago",
    "company": "Meembee",
    "stipend": "$2.50",
    "openings": 66,
    "link1": "nasa.gov",
    "link2": "nba.com"
  }, {
    "id": 5,
    "image": "http://dummyimage.com/139x100.png/ff4444/ffffff",
    "intern_name": "Software Consultant",
    "mode": "In-Office",
    "location": "Sweden",
    "posted": "3 days ago",
    "company": "LiveZ",
    "stipend": "$7.14",
    "openings": 3,
    "link1": "cargocollective.com",
    "link2": "army.mil"
  }, {
    "id": 6,
    "image": "http://dummyimage.com/243x100.png/5fa2dd/ffffff",
    "intern_name": "Technical Writer",
    "mode": "hybrid",
    "location": "New Zealand",
    "posted": "3 days ago",
    "company": "Mynte",
    "stipend": "$9.08",
    "openings": 85,
    "link1": "typepad.com",
    "link2": "kickstarter.com"
  }, {
    "id": 7,
    "image": "http://dummyimage.com/198x100.png/dddddd/000000",
    "intern_name": "Senior Developer",
    "mode": "hybrid",
    "location": "Mongolia",
    "posted": "9 days ago",
    "company": "Zoonoodle",
    "stipend": "$4.02",
    "openings": 42,
    "link1": "elegantthemes.com",
    "link2": "cbsnews.com"
  }, {
    "id": 8,
    "image": "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
    "intern_name": "Staff Scientist",
    "mode": "In-Office",
    "location": "Poland",
    "posted": "5 days ago",
    "company": "Devpulse",
    "stipend": "$5.81",
    "openings": 16,
    "link1": "ning.com",
    "link2": "freewebs.com"
  }, {
    "id": 9,
    "image": "http://dummyimage.com/162x100.png/dddddd/000000",
    "intern_name": "Web Developer IV",
    "mode": "Online",
    "location": "Serbia",
    "posted": "5 days ago",
    "company": "Skivee",
    "stipend": "$4.72",
    "openings": 93,
    "link1": "ucoz.ru",
    "link2": "myspace.com"
  }, {
    "id": 10,
    "image": "http://dummyimage.com/120x100.png/ff4444/ffffff",
    "intern_name": "Developer I",
    "mode": "Online",
    "location": "Mongolia",
    "posted": "1 day ago",
    "company": "Realpoint",
    "stipend": "$0.93",
    "openings": 19,
    "link1": "scribd.com",
    "link2": "diigo.com"
  }, {
    "id": 11,
    "image": "http://dummyimage.com/245x100.png/dddddd/000000",
    "intern_name": "Computer Systems Analyst I",
    "mode": "hybrid",
    "location": "Philippines",
    "posted": "1 day ago",
    "company": "Skidoo",
    "stipend": "$6.75",
    "openings": 88,
    "link1": "indiatimes.com",
    "link2": "ed.gov"
  }, {
    "id": 12,
    "image": "http://dummyimage.com/186x100.png/dddddd/000000",
    "intern_name": "Geologist II",
    "mode": "Online",
    "location": "North Korea",
    "posted": "9 days ago",
    "company": "Tagpad",
    "stipend": "$8.93",
    "openings": 5,
    "link1": "sfgate.com",
    "link2": "ted.com"
  }, {
    "id": 13,
    "image": "http://dummyimage.com/172x100.png/dddddd/000000",
    "intern_name": "Chemical Engineer",
    "mode": "hybrid",
    "location": "Canada",
    "posted": "5 days ago",
    "company": "Kazu",
    "stipend": "$2.95",
    "openings": 62,
    "link1": "oracle.com",
    "link2": "census.gov"
  }, {
    "id": 14,
    "image": "http://dummyimage.com/188x100.png/cc0000/ffffff",
    "intern_name": "Senior Developer",
    "mode": "Online",
    "location": "Yemen",
    "posted": "5 days ago",
    "company": "Topiczoom",
    "stipend": "$8.49",
    "openings": 18,
    "link1": "dagondesign.com",
    "link2": "e-recht24.de"
  }, {
    "id": 15,
    "image": "http://dummyimage.com/219x100.png/cc0000/ffffff",
    "intern_name": "Business Systems Development Analyst",
    "mode": "Online",
    "location": "Greece",
    "posted": "3 days ago",
    "company": "Photobug",
    "stipend": "$5.12",
    "openings": 21,
    "link1": "hatena.ne.jp",
    "link2": "opensource.org"
  }, {
    "id": 16,
    "image": "http://dummyimage.com/210x100.png/5fa2dd/ffffff",
    "intern_name": "Research Nurse",
    "mode": "Online",
    "location": "Indonesia",
    "posted": "1 day ago",
    "company": "Skalith",
    "stipend": "$8.29",
    "openings": 29,
    "link1": "hexun.com",
    "link2": "mayoclinic.com"
  }, {
    "id": 17,
    "image": "http://dummyimage.com/132x100.png/ff4444/ffffff",
    "intern_name": "Geologist IV",
    "mode": "hybrid",
    "location": "Mexico",
    "posted": "5 days ago",
    "company": "Roombo",
    "stipend": "$5.18",
    "openings": 27,
    "link1": "bbb.org",
    "link2": "ameblo.jp"
  }, {
    "id": 18,
    "image": "http://dummyimage.com/184x100.png/dddddd/000000",
    "intern_name": "Automation Specialist I",
    "mode": "hybrid",
    "location": "Yemen",
    "posted": "1 day ago",
    "company": "Nlounge",
    "stipend": "$2.57",
    "openings": 63,
    "link1": "about.me",
    "link2": "webnode.com"
  }, {
    "id": 19,
    "image": "http://dummyimage.com/131x100.png/cc0000/ffffff",
    "intern_name": "Recruiting Manager",
    "mode": "Online",
    "location": "China",
    "posted": "1 day ago",
    "company": "Skiba",
    "stipend": "$6.41",
    "openings": 74,
    "link1": "engadget.com",
    "link2": "surveymonkey.com"
  }, {
    "id": 20,
    "image": "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    "intern_name": "Senior Editor",
    "mode": "Online",
    "location": "Indonesia",
    "posted": "3 days ago",
    "company": "Gigashots",
    "stipend": "$3.49",
    "openings": 17,
    "link1": "illinois.edu",
    "link2": "sbwire.com"
  }]